
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/srv/app/:rw,delegated
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/symfony.ini
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/key.pem:/etc/nginx/ssl/key.pem:ro
      - ./docker/nginx/cert.pem:/etc/nginx/ssl/cert.pem:ro

    environment:
      - APP_ENV=${APP_ENV:-dev}
      - SERVER_NAME=${DOMAIN}
    networks:
      default:
        aliases:
          - ${DOMAIN}

networks:
  default:
    external: true
    name: main-network
